### ISSUE TITLE
lusc_tcga_pub, prad_tcga_pub, 

### ISSUE THREAD

**Issue by asamedy** [waldronlab/MultiAssayExperimentData#2]
Error in .generateMap(pData, experiments) : 
  no way to map pData to ExperimentList 
http://www.cbioportal.org/study?id=lusc_tcga#summary
http://www.cbioportal.org/study?id=prad_tcga#summary

**Comment by LiNk-NY** [comment]
Hi Andy, @asamedy 
This is common in TCGA data because Patient IDs are shorter than Sample IDs but share a common set of identifying information. 
Try using 
```
.generateMap(colData, experiments, TCGAutils::TCGAbarcode)
```

**Comment by asamedy** [comment]
Thanks for the tip Marcel.  Will try that.

**Comment by LiNk-NY** [comment]
I've added a helper to remove any instances of `LUSC` or `[A-Z]{4}` that are not `TCGA` and replace them with `TCGA`.

**Comment by LiNk-NY** [comment]
Oops, wrong commit noted.
